name: Deploy Website

on:
  push:
    branches:
      - main # This triggers the script every time you push to 'main'

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔨 Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: 📂 Sync Files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # Use ./build/ if you are using Create React App
          server-dir: ./public_html/
          protocol: ftp # Try 'ftp' first, then 'ftps' if it fails
          port: 21
